# import Variant from "./Variant.gql"
# import Translation from "./Translation.gql"
type Article {
    title: String
    description: String
    price: Float
    ean: String!
    createdBy: String
    createdAt: String
    lastChangedAt: String
    lastChangedBy: String
    variants: [Variant!]

    priceEUR: String
    priceUSD: String
    priceJPY: String
    priceBGN: String
    priceCZK: String
    priceDKK: String
    priceGBP: String
    priceHUF: String
    pricePLN: String
    priceRON: String
    priceSEK: String
    priceCHF: String
    priceISK: String
    priceNOK: String
    priceHRK: String
    priceRUB: String
    priceTRY: String
    priceAUD: String
    priceBRL: String
    priceCAD: String
    priceCNY: String
    priceHKD: String
    priceIDR: String
    priceILS: String
    priceINR: String
    priceKRW: String
    priceMXN: String
    priceMYR: String
    priceNZD: String
    pricePHP: String
    priceSGD: String
    priceTHB: String
    priceZAR: String

    titleEN: Translation
    titleAR: Translation
    titleZH: Translation
    titleNL: Translation
    titleFI: Translation
    titleFR: Translation
    titleDE: Translation
    titleHI: Translation
    titleHU: Translation
    titleID: Translation
    titleGA: Translation
    titleIT: Translation
    titleJA: Translation
    titleKO: Translation
    titlePL: Translation
    titlePT: Translation
    titleRU: Translation
    titleES: Translation
    titleSV: Translation
    titleTR: Translation
    titleUK: Translation
    titleVI: Translation

    descriptionEN: Translation
    descriptionAR: Translation
    descriptionZH: Translation
    descriptionNL: Translation
    descriptionFI: Translation
    descriptionFR: Translation
    descriptionDE: Translation
    descriptionHI: Translation
    descriptionHU: Translation
    descriptionID: Translation
    descriptionGA: Translation
    descriptionIT: Translation
    descriptionJA: Translation
    descriptionKO: Translation
    descriptionPL: Translation
    descriptionPT: Translation
    descriptionRU: Translation
    descriptionES: Translation
    descriptionSV: Translation
    descriptionTR: Translation
    descriptionUK: Translation
    descriptionVI: Translation
}
