enum language {
    en
    ar
    zh
    nl
    fi
    fr
    de
    hi
    hu
    id
    ga
    it
    ja
    ko
    pl
    pt
    ru
    es
    sv
    tr
    uk
    vi
}
enum field {
    title
    description
    characteristic
}

input TranslationArticleInput {
    ean: String
}

input TranslationVariantInput {
    id: Int
}

input TranslationInput {
    variant: TranslationVariantInput
    language: language!
    article: TranslationArticleInput!
    content: String!
    field: field!
}
